{% set version = '1.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-constructive
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/constructive_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/constructive/constructive_{{ version }}.tar.gz
  sha256: 307a540d91ec486c08f1e1dc82a228c54a6350d07ea635f3252a917a61f3e5f0

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-diffobj
    - r-rlang >=1.0.0
    - r-waldo
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cli
    - r-diffobj
    - r-rlang >=1.0.0
    - r-waldo

test:
  commands:
    - $R -e "library('constructive')"           # [not win]
    - "\"%R%\" -e \"library('constructive')\""  # [win]

about:
  home: https://cynkra.github.io/constructive/
  dev_url: https://github.com/cynkra/constructive
  license: MIT
  summary: Prints code that can be used to recreate R objects. In a sense it is similar to 'base::dput()'
    or 'base::deparse()' but 'constructive' strives to use idiomatic constructors.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: constructive
# Title: Display Idiomatic Code to Construct Most R Objects
# Version: 1.0.1
# Authors@R: c(person(given = "Antoine", family = "Fabri", email = "antoine.fabri@gmail.com", role = c("aut", "cre")), person(given = "Kirill", family = "Muller", role = "ctb", email = "kirill@cynkra.com", comment = c(ORCID = "0000-0002-1416-3412")))
# Description: Prints code that can be used to recreate R objects. In a sense it is similar to 'base::dput()' or 'base::deparse()' but 'constructive' strives to use idiomatic constructors.
# License: MIT + file LICENSE
# URL: https://github.com/cynkra/constructive, https://cynkra.github.io/constructive/
# BugReports: https://github.com/cynkra/constructive/issues
# Imports: cli, diffobj, methods, rlang (>= 1.0.0), waldo
# Suggests: bit64, blob, clipr, data.table, DiagrammeR, DiagrammeRsvg, dm, dplyr, forcats, ggplot2, knitr, lubridate, pixarfilms, prettycode, reprex, rmarkdown, roxygen2, rstudioapi, scales, sf, testthat (>= 3.0.0), tibble, tidyselect, vctrs, withr
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# NeedsCompilation: yes
# Packaged: 2024-07-06 22:12:50 UTC; Antoine
# Author: Antoine Fabri [aut, cre], Kirill Muller [ctb] (<https://orcid.org/0000-0002-1416-3412>)
# Maintainer: Antoine Fabri <antoine.fabri@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-07-07 09:40:02 UTC
